services:
  postgres:
    image: postgres:15
    container_name: taskflow-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=flowtask_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Siddhi24
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d flowtask_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - taskflow-network

  backend:
    image: siddhi245/taskflow-backend:latest
    container_name: taskflow-backend
    ports:
      - "8081:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/flowtask_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=Siddhi24
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - taskflow-network

  frontend:
    image: siddhi245/taskflow-frontend:latest
    container_name: taskflow-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - taskflow-network

volumes:
  postgres-data:

networks:
  taskflow-network:
    driver: bridge